### ISSUE TITLE
Rebrand?

### ISSUE THREAD

**Issue by bertob** [GeopJr/Collision#26]
The current branding has a few problems:
- Many people have no idea what kind of "hashbrown" the name refers to, I thought it was about actual hash brownies :D 
- People think the icon is an egg or something weather related, the "food in paper bag" idea is not really getting across
- The current icon is low contrast and needs better execution

I'm not sure what we can do about the name, I guess there's no way to avoid the drug association without completely changing the metaphor. I'd be happy to help brainstorm something else, but maybe keeping the name is fine if we make the icon something more generic and less weird for people who don't know the type of food this references.

Here's a concept for a more generic icon:

![image](https://user-images.githubusercontent.com/1908896/144723075-f64eb86a-fd4c-4f6e-ae4e-b61dbcc5b926.png)

Since this app is already in Circle and on apps.gnome.org it'd be good to get this fixed sooner rather than later.

cc @jimmac @sophie-h

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Just to clarify in advance, both the name and icon for Hashbrown, refer to the [food item](https://en.wikipedia.org/wiki/Hash_browns).

<details><summary>The icon is inspired by the following images:</summary>

![mcdonalds hashbrown in paper bag](https://thefoodxp.com/wp-content/uploads/2021/01/hashbrown-e1610360267826.jpg)
![mcdonalds hashbrown in paper bag standing](https://149449860.v2.pressablecdn.com/wp-content/uploads/2019/02/RC-NEWS-Hashbrown-or-cellphone-0319.png)

</details>

I hadn't noticed the drug association until now and would be happy to sort it out as soon as possible.

That being said, a rebrand sounds nice! The generic icon perfectly summarizes the app's functionality and looks good (thanks!), but I'm not sure about the name. "Hashbrown" will no longer be associated with the app icon and feels a bit out of place (similarly to if "lollypop" was just a "play" icon). At the same time I can't really think of an [appropriate name](https://developer.gnome.org/hig/guidelines/app-naming.html). Some thoughts:

- "Hash Generator" (too generic?)
- "Collision" ([ref](https://en.wikipedia.org/wiki/Hash_collision))
- "Checksum"

I'm ok with keeping "Hashbrown" too, since changing it will require additional work outside the app itself (Flathub, third-party repos, Software, Circle, other websites).

**Comment by bertob** [comment]
Collision sounds really cool, and would work well here IMO.

**Comment by GeopJr** [comment]
Started tracking it on #27. Unless there are any objections to the rename (and the chosen name, `Collision`), I'm ready to proceed with the tasks.

**Comment by sophie-h** [comment]
[Renamed in Circle repo](https://gitlab.gnome.org/Teams/Circle/-/issues/113). Please report changes like this to the Circle Committee.

**Comment by GeopJr** [comment]
Oops, really sorry about that. I completely lost track of it after #27 got merged.
(Also didn't get the gitlab notification due to "Your account had been deactivated due to inactivity").

Just [submited the last issue of](https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1301) #27. Again super sorry about this, won't happen again.
